baseURL: "https://richardalmanza.com"
languageCode: "en-us"
title: "Richard Almanza"
theme: fork-hugo-profile

# Multilingual configuration
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: true

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

enableRobotsTXT: true

#services:
  #googleAnalytics:
    #id: G-MEASUREMENT_ID
  #disqus:
    #shortname: your-disqus-shortname

pagination:
  pagerSize: 3

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
    # - identifier: gallery
    #   name: Gallery
    #   title: Gallery
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2
